services:
    blindsqli:
        build: . 
        container_name: ducktableslqi
        working_dir: /usr/src
        volumes:
            - ./src/:/usr/src
            - /usr/src/node_modules
        ports:
            - "9000:3000"
        environment:
            - FLAG=quack{s0_a_bl1nd_duck_w4lks_1nt0_a_t4bl3_4nd_s4y5_wh0_m0v3d_th3_p0nd?}
        restart: on-failure:10
        healthcheck:
          test: curl --fail http://localhost:3000/health || exit 1
          interval: 60s
          timeout: 30s
          retries: 3
          start_period: 60s
        resources:
            limits:
            cpus: '0.5'