version: '3'

services:
  web:
    build: ./app
    image: master-image
    container_name: web_headless_chicken_web
    volumes:
      - ./app:/app
    ports:
      - 1337:5000
    command: /usr/local/bin/gunicorn -b :5000 main:app

  worker:
    image: master-image
    container_name: web_headless_chicken_worker
    depends_on:
      - redis
    command: rqworker --name worker --url redis://redis:6379/0

# uncomment to have a another worker
#  worker2:
#    image: master-image
#    depends_on:
#      - redis
#    command: rqworker --name worker2 --url redis://redis:6379/0

  redis:
    container_name: web_headless_chicken_redis
    image: redis
