

# This file was *autogenerated* from the file script.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1000 = Integer(1000); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
flag = b"quack{50M3T1m35_4Ll_Y0U_n33D_15_4_l1ttl3_150M0rPH15m!}"

n = _sage_const_1000 
theta = _sage_const_2 *pi/n
a = cos(theta)
b = sin(theta)

M = matrix([[a, -b], [b, a]])

print((M**flag[_sage_const_0 ] * M**flag[_sage_const_1 ] * M**flag[_sage_const_2 ]).n())
print((M**flag[_sage_const_2 ] * M**flag[_sage_const_1 ]).n())
print((M**flag[_sage_const_1 ] * M**flag[_sage_const_0 ]).n())

S = []
for i in range(_sage_const_1 ):
  s = identity_matrix(_sage_const_2 )
  for j in range(i+_sage_const_1 ):
    s *= M**(flag[j])

  S.append(s.n())

#print(S)

